import {request} from './client';import type {AdminCourseOfferingListItem,AdminCourseOfferingSummary,AdminDashboard,AdminStudentListItem,AdminStudentSummary} from '../types';
interface StudentRecord{id:string;matriculation_number:string;first_name:string;last_name:string;programme_id:string;current_level:string|null;enrollment_status:string}
interface ProgrammeRecord{id:string;name:string}
interface OfferingRecord{id:string;course_id:string;academic_session_id:string;semester_id:string;status:string;registration_open:boolean}
interface CourseRecord{id:string;code:string;title:string;credit_units:number}
interface NamedRecord{id:string;name:string}
async function students():Promise<AdminStudentListItem[]>{const [records,programmes]=await Promise.all([request<StudentRecord[]>('/students'),request<ProgrammeRecord[]>('/programmes')]);const names=new Map(programmes.map(p=>[p.id,p.name]));return records.map(student=>({...student,programme_name:names.get(student.programme_id)??'Programme unavailable'}))}
async function offerings():Promise<AdminCourseOfferingListItem[]>{const [records,courses,sessions,semesters]=await Promise.all([request<OfferingRecord[]>('/course-offerings'),request<CourseRecord[]>('/courses'),request<NamedRecord[]>('/academic-sessions'),request<NamedRecord[]>('/semesters')]);const courseMap=new Map(courses.map(c=>[c.id,c]));const sessionMap=new Map(sessions.map(s=>[s.id,s.name]));const semesterMap=new Map(semesters.map(s=>[s.id,s.name]));return records.map(offering=>{const course=courseMap.get(offering.course_id);return{id:offering.id,course_code:course?.code??'—',course_title:course?.title??'Course unavailable',credit_units:course?.credit_units??null,academic_session:sessionMap.get(offering.academic_session_id)??'—',semester:semesterMap.get(offering.semester_id)??'—',status:offering.status,registration_open:offering.registration_open}})}
export const adminApi={dashboard:()=>request<AdminDashboard>('/admin-portal/dashboard'),students,offerings,student:(id:string)=>request<AdminStudentSummary>(`/admin-portal/students/${encodeURIComponent(id)}/summary`),offering:(id:string)=>request<AdminCourseOfferingSummary>(`/admin-portal/course-offerings/${encodeURIComponent(id)}/summary`)};
