import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';const read=p=>readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
test('Student More actions use native presses and real routes',()=>{const page=read('app/student/more.tsx');assert.match(page,/ActionCard/);assert.ok(page.includes('onPress={()=>router.push'));assert.doesNotMatch(page,/\bLink\b|asChild/);for(const route of ['attendance','performance','transcript','clearance','documents'])assert.match(page,new RegExp(route))});
test('Student Course cards navigate directly to authorized materials',()=>{const courses=read('app/student/courses.tsx'),materials=read('app/student/course/[id]/materials.tsx');assert.match(courses,/ActionCard/);assert.match(courses,/router\.push\(`\/student\/course\/\$\{offeringId\}\/materials`/);assert.doesNotMatch(courses,/\bLink\b|asChild/);assert.match(materials,/studentApi\.materials\(id\)/);assert.match(materials,/uploaded_file/);assert.match(materials,/external_url/);assert.doesNotMatch(materials,/createMaterial|publishMaterial|deleteMaterial|uploadCourseMaterial/)});
test('Student Home is a deliberate identity and academic snapshot',()=>{const page=read('app/student/index.tsx');assert.match(page,/Academic snapshot/);for(const value of ['full_name','matriculation_number','programme_name','current_level','current_gpa','cgpa','academic_standing','registered_course_count'])assert.match(page,new RegExp(value));assert.doesNotMatch(page,/student_id|programme_id|DetailScreen|RecordCard/)});
test('Student visible tabs use supported Ionicons',()=>{const layout=read('app/student/_layout.tsx');for(const icon of ['home-outline','book-outline','school-outline','ellipsis-horizontal-circle-outline'])assert.match(layout,new RegExp(`icon:'${icon}'`))});
test('Student More leaves profile detail and logout available',()=>{const more=read('app/student/more.tsx'),account=read('src/components/MoreScreen.tsx');for(const field of ['matriculation_number','programme_name','admission_year','enrollment_status'])assert.match(more,new RegExp(field));assert.match(account,/Log out/);assert.match(account,/logout\(\)/)});
test('Student nested records have deterministic Back actions',()=>{for(const route of ['attendance','performance','transcript','clearance','documents']){const page=read(`app/student/${route}.tsx`);assert.match(page,/BackAction label="More" href="\/student\/more"/)}assert.match(read('app/student/course/[id]/materials.tsx'),/BackAction label="Courses" href="\/student\/courses"/)});
test('Student academic detail screens whitelist visible fields and hide internal IDs',()=>{const apiScreens=read('src/components/ApiScreens.tsx');assert.match(apiScreens,/fields\?:string\[\]/);assert.match(apiScreens,/RecordCard record=\{q\.data\} fields=\{fields\}/);for(const route of ['performance','transcript','clearance']){const page=read(`app/student/${route}.tsx`);assert.match(page,/fields=\{fields\}/);assert.doesNotMatch(page,/['"](?:student_id|programme_id|academic_level_id|academic_session_id|session_id|semester_id|result_id|registration_id|course_registration_id)['"]/)}for(const route of ['attendance','results','documents']){const page=read(`app/student/${route}.tsx`);assert.match(page,/fields=\{\[/);assert.doesNotMatch(page,/['"](?:student_id|programme_id|academic_level_id|academic_session_id|session_id|semester_id|result_id|registration_id|course_registration_id)['"]/)}assert.doesNotMatch(read('app/student/index.tsx'),/student_id|programme_id|academic_level_id|session_id|semester_id|result_id|registration_id/)});
test('Student-facing labels normalize Programme and academic acronyms',()=>{const ui=read('src/components/UI.tsx');assert.match(ui,/programme_name:'Programme'/);assert.match(ui,/cgpa:'CGPA'/);assert.match(ui,/gpa:'GPA'/);assert.match(ui,/current_gpa:'Current GPA'/);assert.match(ui,/value\.includes\('_'\)/)});
