import {authStorage} from '../storage/authStorage';
const configuredApiBaseUrl=process.env.EXPO_PUBLIC_API_BASE_URL?.trim();
export const isPreviewBuild=process.env.EXPO_PUBLIC_BUILD_PROFILE==='preview';
export const apiConfigurationError=!configuredApiBaseUrl?'API base URL is not configured for this build.':!/^https?:\/\/[^/]+(?:\/.*)?\/api\/v1\/?$/.test(configuredApiBaseUrl)?'API base URL must be an absolute HTTP(S) URL ending in /api/v1.':undefined;
export const apiBaseUrl=apiConfigurationError?'':configuredApiBaseUrl!.replace(/\/$/,'');
export const apiUrl=(path:string)=>{if(apiConfigurationError)throw new ApiError(apiConfigurationError,0);return `${apiBaseUrl}${path.startsWith('/')?path:`/${path}`}`};
if(isPreviewBuild&&!apiConfigurationError)console.info(`[Ngozi Smart Campus] API: ${apiBaseUrl}`);
let unauthorized:(()=>void)|undefined;
export class ApiError extends Error{constructor(message:string,public status:number){super(message);this.name='ApiError'}}
export const setUnauthorizedHandler=(handler:(()=>void)|undefined)=>{unauthorized=handler};
export async function request<T>(path:string,options:RequestInit={}):Promise<T>{const token=await authStorage.getToken();const headers=new Headers(options.headers);headers.set('Accept','application/json');if(options.body&&!(options.body instanceof FormData)&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');if(token)headers.set('Authorization',`Bearer ${token}`);let response:Response;try{response=await fetch(apiUrl(path),{...options,headers})}catch(error){if(error instanceof ApiError)throw error;throw new ApiError('Unable to reach the campus service. Check your connection and try again.',0)}if(response.status===401){await authStorage.clear();unauthorized?.()}if(!response.ok){let body:unknown;try{body=await response.json()}catch{body=null}const detail=body&&typeof body==='object'&&'detail' in body&&typeof body.detail==='string'?body.detail:undefined;const message=response.status===403||response.status===404?'This information is unavailable or you do not have access.':detail??'The request could not be completed.';throw new ApiError(message,response.status)}return response.status===204?undefined as T:response.json() as Promise<T>}
