from fastapi import APIRouter

from app.api.v1.endpoints import (
    assessment_components_router,
    assessment_scores_router,
    examinations_router,
    examination_scores_router,
    academic_levels_router,
    academic_sessions_router,
    attendance_records_router,
    attendance_analytics_router,
    auth_router,
    courses_router,
    course_offerings_router,
    course_registrations_router,
    class_sessions_router,
    departments_router,
    faculties_router,
    lecturers_router,
    lecturer_assignments_router,
    programmes_router,
    semesters_router,
    students_router,
    result_computation_router,
    results_router,
    academic_performance_router,
    academic_progression_router,
    transcripts_router,
    official_transcripts_router,
    graduation_eligibility_router,
    degree_classification_router,
    graduations_router,
    academic_documents_router,
    public_academic_documents_router,
)


api_router = APIRouter()
api_router.include_router(assessment_components_router)
api_router.include_router(assessment_scores_router)
api_router.include_router(examinations_router)
api_router.include_router(examination_scores_router)
api_router.include_router(result_computation_router)
api_router.include_router(results_router)
api_router.include_router(academic_performance_router)
api_router.include_router(academic_progression_router)
api_router.include_router(transcripts_router)
api_router.include_router(official_transcripts_router)
api_router.include_router(graduation_eligibility_router)
api_router.include_router(degree_classification_router)
api_router.include_router(graduations_router)
api_router.include_router(academic_documents_router)
api_router.include_router(public_academic_documents_router)
api_router.include_router(auth_router)
api_router.include_router(attendance_records_router)
api_router.include_router(attendance_analytics_router)
api_router.include_router(courses_router)
api_router.include_router(course_offerings_router)
api_router.include_router(course_registrations_router)
api_router.include_router(class_sessions_router)
api_router.include_router(academic_levels_router)
api_router.include_router(academic_sessions_router)
api_router.include_router(semesters_router)
api_router.include_router(faculties_router)
api_router.include_router(lecturers_router)
api_router.include_router(lecturer_assignments_router)
api_router.include_router(departments_router)
api_router.include_router(programmes_router)
api_router.include_router(students_router)
