import type {ReactNode} from 'react';import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';import {SafeAreaView} from 'react-native-safe-area-context';import {colors,radius,spacing} from '../theme';
export function Screen({children,title}:{children:ReactNode;title?:string}){return <SafeAreaView edges={['top','left','right']} style={s.safe}><ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={s.screen}>{title&&<Text accessibilityRole="header" style={s.title}>{title}</Text>}{children}</ScrollView></SafeAreaView>}
export const LoadingState=()=> <View style={s.state} accessibilityRole="progressbar"><ActivityIndicator color={colors.green}/><Text>Loading…</Text></View>;
export const ErrorState=({message,onRetry}:{message:string;onRetry?:()=>void})=><View style={s.state}><Text accessibilityRole="alert" style={s.error}>{message}</Text>{onRetry&&<PrimaryButton title="Try again" onPress={onRetry}/>}</View>;
export const EmptyState=({message='No records are available yet.'}:{message?:string})=><View style={s.state}><Text style={s.muted}>{message}</Text></View>;
export function PrimaryButton({title,onPress,disabled=false}:{title:string;onPress:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,(pressed||disabled)&&s.dim]}><Text style={s.buttonText}>{title}</Text></Pressable>}
export const StatCard=({label,value}:{label:string;value:unknown})=><View style={s.stat}><Text style={s.muted}>{human(label)}</Text><Text style={s.statValue}>{display(value)}</Text></View>;
export const StatusBadge=({value}:{value:unknown})=><View style={s.badge}><Text style={s.badgeText}>{display(value)}</Text></View>;
export const InfoCard=({children}:{children:ReactNode})=><View style={s.card}>{children}</View>;
export function ActionCard({children,onPress,label}:{children:ReactNode;onPress:()=>void;label:string}){return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={({pressed})=>[s.card,s.actionCard,pressed&&s.pressed]}>{children}</Pressable>}
export const SectionHeader=({children}:{children:string})=><Text accessibilityRole="header" style={s.section}>{children}</Text>;
export function RecordCard({record,fields}:{record:Record<string,unknown>;fields?:string[]}){const entries=(fields??Object.keys(record)).filter(k=>record[k]!==undefined&&record[k]!==null&&typeof record[k]!=='object');return <InfoCard>{entries.map(k=><View key={k} style={s.row}><Text style={s.key}>{human(k)}</Text><Text style={s.value}>{display(record[k])}</Text></View>)}</InfoCard>}
export const display=(value:unknown)=>value===null||value===undefined||value===''?'—':typeof value==='boolean'?(value?'Yes':'No'):typeof value==='string'&&value.includes('_')?value.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase()):String(value);const human=(v:string)=>({programme_name:'Programme',cgpa:'CGPA',gpa:'GPA',current_gpa:'Current GPA'}[v]??v.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase()));
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},screen:{width:'100%',padding:spacing.md,paddingBottom:spacing.lg,gap:spacing.md},title:{fontSize:28,fontWeight:'800',color:colors.green},section:{fontSize:19,fontWeight:'700',color:colors.text,marginTop:spacing.sm},card:{backgroundColor:colors.surface,borderRadius:radius.md,padding:spacing.md,gap:spacing.sm,borderWidth:1,borderColor:colors.border},actionCard:{minHeight:64},pressed:{opacity:.68,transform:[{scale:.99}]},row:{gap:2},key:{fontSize:12,color:colors.muted,fontWeight:'600'},value:{fontSize:16,color:colors.text},state:{minHeight:160,alignItems:'center',justifyContent:'center',gap:spacing.md,padding:spacing.lg},error:{color:colors.danger,textAlign:'center'},muted:{color:colors.muted},button:{minHeight:48,backgroundColor:colors.green,borderRadius:radius.md,alignItems:'center',justifyContent:'center',paddingHorizontal:spacing.lg},buttonText:{color:'white',fontSize:16,fontWeight:'700'},dim:{opacity:.65},stat:{backgroundColor:colors.surface,borderLeftWidth:4,borderLeftColor:colors.gold,borderRadius:radius.md,padding:spacing.md,minWidth:'46%',flexGrow:1},statValue:{fontSize:21,fontWeight:'800',color:colors.text,marginTop:4},badge:{alignSelf:'flex-start',backgroundColor:colors.greenSoft,paddingHorizontal:10,paddingVertical:5,borderRadius:99},badgeText:{color:colors.green,fontWeight:'700'}});
