"""create digital library

Revision ID: b16d1f0a2026
Revises: a15c0e9f2026
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="b16d1f0a2026";down_revision="a15c0e9f2026";branch_labels=None;depends_on=None
UUID=postgresql.UUID(as_uuid=True)
def timestamps():return [sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False)]
def indexes(table,*columns):
    for column in columns:op.create_index(op.f(f"ix_{table}_{column}"),table,[column])
def upgrade():
    op.create_table("library_categories",sa.Column("institution_id",UUID,nullable=False),sa.Column("name",sa.String(150),nullable=False),sa.Column("description",sa.Text()),sa.Column("parent_id",UUID),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("id",UUID,nullable=False),*timestamps(),sa.ForeignKeyConstraint(["institution_id"],["institutions.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["parent_id"],["library_categories.id"],ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("institution_id","name",name="uq_library_categories_institution_name"));indexes("library_categories","institution_id","parent_id","is_active")
    op.create_table("authors",sa.Column("institution_id",UUID,nullable=False),sa.Column("first_name",sa.String(100)),sa.Column("last_name",sa.String(100)),sa.Column("display_name",sa.String(255),nullable=False),sa.Column("id",UUID,nullable=False),*timestamps(),sa.ForeignKeyConstraint(["institution_id"],["institutions.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("institution_id","display_name",name="uq_authors_institution_display_name"));indexes("authors","institution_id","display_name")
    op.create_table("library_items",sa.Column("institution_id",UUID,nullable=False),sa.Column("title",sa.String(255),nullable=False),sa.Column("subtitle",sa.String(255)),sa.Column("description",sa.Text()),sa.Column("item_type",sa.String(30),nullable=False),sa.Column("isbn",sa.String(30)),sa.Column("edition",sa.String(80)),sa.Column("publisher",sa.String(255)),sa.Column("publication_year",sa.Integer()),sa.Column("language",sa.String(80),nullable=False),sa.Column("category_id",UUID),sa.Column("cover_image_url",sa.String(2048)),sa.Column("access_type",sa.String(20),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_by_user_id",UUID,nullable=False),sa.Column("source_type",sa.String(30)),sa.Column("original_filename",sa.String(255)),sa.Column("mime_type",sa.String(150)),sa.Column("file_size",sa.Integer()),sa.Column("file_reference",sa.String(500)),sa.Column("external_url",sa.String(2048)),sa.Column("sha256",sa.String(64)),sa.Column("uploaded_at",sa.DateTime(timezone=True)),sa.Column("id",UUID,nullable=False),*timestamps(),sa.CheckConstraint("item_type IN ('book','ebook','journal','article','thesis','report','lecture_reference','other')",name=op.f("ck_library_items_library_item_type")),sa.CheckConstraint("access_type IN ('physical','digital','hybrid')",name=op.f("ck_library_items_library_item_access_type")),sa.CheckConstraint("status IN ('active','inactive','archived')",name=op.f("ck_library_items_library_item_status")),sa.CheckConstraint("source_type IS NULL OR source_type IN ('uploaded_file','external_url')",name=op.f("ck_library_items_library_item_source_type")),sa.CheckConstraint("publication_year IS NULL OR publication_year BETWEEN 1000 AND 9999",name=op.f("ck_library_items_library_item_publication_year")),sa.ForeignKeyConstraint(["institution_id"],["institutions.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["category_id"],["library_categories.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["created_by_user_id"],["users.id"],ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("institution_id","isbn",name="uq_library_items_institution_isbn"));indexes("library_items","institution_id","title","item_type","isbn","publisher","publication_year","category_id","access_type","status","source_type")
    op.create_table("library_item_authors",sa.Column("institution_id",UUID,nullable=False),sa.Column("library_item_id",UUID,nullable=False),sa.Column("author_id",UUID,nullable=False),sa.Column("author_order",sa.Integer(),nullable=False),sa.Column("id",UUID,nullable=False),sa.CheckConstraint("author_order > 0",name=op.f("ck_library_item_authors_library_item_author_order")),sa.ForeignKeyConstraint(["institution_id"],["institutions.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["library_item_id"],["library_items.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["author_id"],["authors.id"],ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("library_item_id","author_id",name="uq_library_item_authors_pair"),sa.UniqueConstraint("library_item_id","author_order",name="uq_library_item_authors_order"));indexes("library_item_authors","institution_id","library_item_id","author_id")
    op.create_table("library_copies",sa.Column("institution_id",UUID,nullable=False),sa.Column("library_item_id",UUID,nullable=False),sa.Column("accession_number",sa.String(100),nullable=False),sa.Column("barcode",sa.String(100)),sa.Column("shelf_location",sa.String(150)),sa.Column("acquisition_date",sa.Date()),sa.Column("condition",sa.String(20),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("id",UUID,nullable=False),*timestamps(),sa.CheckConstraint("condition IN ('new','good','fair','poor','damaged')",name=op.f("ck_library_copies_library_copy_condition")),sa.CheckConstraint("status IN ('available','borrowed','reserved','lost','damaged','withdrawn')",name=op.f("ck_library_copies_library_copy_status")),sa.ForeignKeyConstraint(["institution_id"],["institutions.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["library_item_id"],["library_items.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("institution_id","accession_number",name="uq_library_copies_institution_accession"),sa.UniqueConstraint("institution_id","barcode",name="uq_library_copies_institution_barcode"));indexes("library_copies","institution_id","library_item_id","status")
    op.create_table("library_loans",sa.Column("institution_id",UUID,nullable=False),sa.Column("copy_id",UUID,nullable=False),sa.Column("borrower_user_id",UUID,nullable=False),sa.Column("borrowed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("returned_at",sa.DateTime(timezone=True)),sa.Column("status",sa.String(20),nullable=False),sa.Column("issued_by_user_id",UUID,nullable=False),sa.Column("returned_to_user_id",UUID),sa.Column("id",UUID,nullable=False),*timestamps(),sa.CheckConstraint("status IN ('borrowed','returned','overdue','lost')",name=op.f("ck_library_loans_library_loan_status")),sa.CheckConstraint("due_at > borrowed_at",name=op.f("ck_library_loans_library_loan_due_date")),sa.ForeignKeyConstraint(["institution_id"],["institutions.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["copy_id"],["library_copies.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["borrower_user_id"],["users.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["issued_by_user_id"],["users.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["returned_to_user_id"],["users.id"],ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id"));indexes("library_loans","institution_id","copy_id","borrower_user_id","due_at","status");op.create_index("uq_library_loans_active_copy","library_loans",["copy_id"],unique=True,postgresql_where=sa.text("returned_at IS NULL AND status IN ('borrowed','overdue')"))
def downgrade():
    op.drop_table("library_loans");op.drop_table("library_copies");op.drop_table("library_item_authors");op.drop_table("library_items");op.drop_table("authors");op.drop_table("library_categories")
