import {Link,Navigate,useNavigate,useParams} from 'react-router-dom';import {guardianApi} from '../api/guardian';import {DataTable,ObjectDetails,PageHeader,StatCard,StatusBadge} from '../components/UI';import {EmptyState,ErrorState,LoadingState} from '../components/States';import {useApi} from '../hooks/useApi';import type {ClearanceItem,GuardianChild,StudentAttendanceSummary,StudentResult,TranscriptCourse} from '../types';
function AsyncPage<T>({title,load,children}:{title?:string;load:()=>Promise<T>;children:(data:T)=>React.ReactNode}){const {data,error,loading}=useApi(load);return <section>{title&&<PageHeader title={title}/>} {loading?<LoadingState/>:error?<ErrorState error={error}/>:data!==undefined?children(data):<EmptyState/>}</section>}
export function ChildSelector({children}:{children:GuardianChild[]}){const {studentId}=useParams();const navigate=useNavigate();return <label className="child-selector">Child <select aria-label="Select child" value={studentId??''} onChange={e=>navigate(`/guardian/children/${e.target.value}`)}><option value="" disabled>Select a linked child</option>{children.map(c=><option key={c.student_id} value={c.student_id}>{c.student_name} · {c.matriculation_number}</option>)}</select></label>}
function ChildPage({title,render}:{title:string;render:(id:string)=>React.ReactNode}){const {studentId}=useParams();const children=useApi(guardianApi.children);if(children.loading)return <LoadingState/>;if(children.error)return <ErrorState error={children.error}/>;if(!studentId)return <Navigate to="/guardian/children" replace/>;return <section><PageHeader title={title}/><ChildSelector>{children.data??[]}</ChildSelector><nav className="tabs" aria-label="Child academic sections">{[['','Overview'],['results','Results'],['attendance','Attendance'],['performance','Performance'],['transcript','Transcript'],['clearance','Clearance']].map(([to,label])=><Link key={to} to={`/guardian/children/${studentId}${to?`/${to}`:''}`}>{label}</Link>)}</nav>{render(studentId)}</section>}
function Children({rows}:{rows:GuardianChild[]}){return <DataTable rows={rows} columns={[{key:'student_name',label:'Student',render:r=><Link to={`/guardian/children/${r.student_id}`}>{r.student_name}</Link>},{key:'matriculation_number',label:'Matriculation number'},{key:'programme_name',label:'Programme'},{key:'current_level',label:'Level'},{key:'enrollment_status',label:'Status',render:r=><StatusBadge value={r.enrollment_status}/>} ]}/>}
export const GuardianDashboardPage=()=> <AsyncPage title="Guardian dashboard" load={guardianApi.dashboard}>{d=><><p className="welcome">Welcome, {d.guardian_name}. Select a linked child to view permitted academic information.</p><div className="stats"><StatCard label="Verified children" value={d.child_count}/></div><Children rows={d.children}/></>}</AsyncPage>;
export const GuardianChildrenPage=()=> <AsyncPage title="Linked children" load={guardianApi.children}>{rows=><Children rows={rows}/>}</AsyncPage>;
export const ChildOverviewPage=()=> <ChildPage title="Child overview" render={id=><AsyncPage load={()=>guardianApi.overview(id)}>{d=><div className="stats"><StatCard label="Student" value={d.child.student_name}/><StatCard label="Programme" value={d.child.programme_name}/><StatCard label="Level" value={d.child.current_level}/><StatCard label="Published results" value={d.result_count}/><StatCard label="Attendance" value={d.attendance_percentage?`${d.attendance_percentage}%`:null}/><StatCard label="GPA" value={d.current_gpa}/><StatCard label="CGPA" value={d.cgpa}/><StatCard label="Standing" value={d.academic_standing}/></div>}</AsyncPage>}/>;
export const ChildResultsPage=()=> <ChildPage title="Published results" render={id=><AsyncPage load={()=>guardianApi.results(id)}>{rows=><DataTable<StudentResult> rows={rows} columns={[{key:'course_code',label:'Code'},{key:'course_title',label:'Course'},{key:'academic_session',label:'Session'},{key:'semester',label:'Semester'},{key:'credit_units',label:'Units'},{key:'final_score',label:'Score'},{key:'grade',label:'Grade'}]}/>}</AsyncPage>}/>;
export const ChildAttendancePage=()=> <ChildPage title="Attendance" render={id=><AsyncPage load={()=>guardianApi.attendance(id)}>{rows=><DataTable<StudentAttendanceSummary> rows={rows} columns={[{key:'course_code',label:'Code'},{key:'course_title',label:'Course'},{key:'total_sessions',label:'Sessions'},{key:'present_count',label:'Present'},{key:'absent_count',label:'Absent'},{key:'late_count',label:'Late'},{key:'attendance_percentage',label:'Attendance',render:r=>`${r.attendance_percentage}%`}]}/>}</AsyncPage>}/>;
export const ChildPerformancePage=()=> <ChildPage title="Academic performance" render={id=><AsyncPage load={()=>guardianApi.performance(id)}>{d=><><div className="stats"><StatCard label="GPA" value={d.current_gpa}/><StatCard label="CGPA" value={d.cgpa}/><StatCard label="Attempted units" value={d.cumulative_attempted_units}/><StatCard label="Earned units" value={d.cumulative_earned_units}/><StatCard label="Standing" value={d.academic_standing}/></div><article className="panel"><h2>Failed or carryover courses</h2><ObjectDetails value={d.failed_courses}/></article></>}</AsyncPage>}/>;
export const ChildTranscriptPage=()=> <ChildPage title="Computed transcript" render={id=><AsyncPage load={()=>guardianApi.transcript(id)}>{d=><>{d.academic_sessions.length?d.academic_sessions.map(s=><section className="panel" key={s.academic_session_id}><h2>{s.academic_session_name}</h2>{s.semesters.map(x=><section key={x.semester_id}><h3>{x.semester_name} · GPA {x.gpa}</h3><DataTable<TranscriptCourse> rows={x.courses} columns={[{key:'course_code',label:'Code'},{key:'course_title',label:'Course'},{key:'credit_units',label:'Units'},{key:'final_score',label:'Score'},{key:'grade_letter',label:'Grade'}]}/></section>)}</section>):<EmptyState/>}</>}</AsyncPage>}/>;
export const ChildClearancePage=()=> <ChildPage title="Clearance" render={id=><AsyncPage load={()=>guardianApi.clearance(id)}>{d=><><div className="stats"><StatCard label="Overall status" value={<StatusBadge value={d.is_fully_cleared?'Fully cleared':'Pending'}/>}/><StatCard label="Pending" value={d.pending_count}/></div><DataTable<ClearanceItem> rows={d.requirements} columns={[{key:'name',label:'Requirement'},{key:'code',label:'Code'},{key:'is_mandatory',label:'Type',render:r=>r.is_mandatory?'Mandatory':'Optional'},{key:'status',label:'Status'}]}/></>}</AsyncPage>}/>;
