import {studentApi} from '../api/student';import {DataTable,ObjectDetails,PageHeader,StatCard,StatusBadge} from '../components/UI';import {EmptyState,ErrorState,LoadingState} from '../components/States';import {useApi} from '../hooks/useApi';import type {ClearanceItem,StudentAttendanceSummary,StudentCourse,StudentDocument,StudentResult,TranscriptCourse} from '../types';
import {StudentOverview} from '../components/StudentOverview';
function AsyncPage<T>({title,load,children}:{title:string;load:()=>Promise<T>;children:(data:T)=>React.ReactNode}){const {data,error,loading}=useApi(load);return <section><PageHeader title={title}/>{loading?<LoadingState/>:error?<ErrorState error={error}/>:data!==undefined?children(data):<EmptyState/>}</section>}
export const StudentDashboardPage=()=> <AsyncPage title="Dashboard" load={studentApi.dashboard}>{d=><StudentOverview data={d}/>}</AsyncPage>;
export const StudentProfilePage=()=> <AsyncPage title="Profile" load={studentApi.profile}>{d=><article className="panel"><ObjectDetails value={d} hideIds/></article>}</AsyncPage>;
export const StudentCoursesPage=()=> <AsyncPage title="My courses" load={studentApi.courses}>{rows=><DataTable<StudentCourse> rows={rows} columns={[{key:'course_code',label:'Code'},{key:'title',label:'Course'},{key:'credit_units',label:'Units'},{key:'course_type',label:'Type'},{key:'semester',label:'Semester'},{key:'registration_status',label:'Status',render:r=><StatusBadge value={r.registration_status}/>} ]}/>}</AsyncPage>;
export const StudentAttendancePage=()=> <AsyncPage title="Attendance" load={studentApi.attendance}>{rows=><DataTable<StudentAttendanceSummary> rows={rows} columns={[{key:'course_code',label:'Code'},{key:'course_title',label:'Course'},{key:'total_sessions',label:'Sessions'},{key:'present_count',label:'Present'},{key:'absent_count',label:'Absent'},{key:'late_count',label:'Late'},{key:'attendance_percentage',label:'Attendance',render:r=>`${r.attendance_percentage}%`} ]}/>}</AsyncPage>;
export const StudentResultsPage=()=> <AsyncPage title="Results" load={studentApi.results}>{rows=><DataTable<StudentResult> rows={rows} columns={[{key:'course_code',label:'Code'},{key:'course_title',label:'Course'},{key:'academic_session',label:'Session'},{key:'semester',label:'Semester'},{key:'credit_units',label:'Units'},{key:'final_score',label:'Score'},{key:'grade',label:'Grade'},{key:'passed',label:'Outcome',render:r=><StatusBadge value={r.passed?'Passed':'Not passed'}/>} ]}/>}</AsyncPage>;
export const StudentPerformancePage=()=> <AsyncPage title="Academic performance" load={studentApi.performance}>{d=><><div className="stats"><StatCard label="GPA" value={d.current_gpa}/><StatCard label="CGPA" value={d.cgpa}/><StatCard label="Attempted units" value={d.cumulative_attempted_units}/><StatCard label="Earned units" value={d.cumulative_earned_units}/><StatCard label="Standing" value={d.academic_standing}/></div><article className="panel"><h2>Progression</h2><ObjectDetails value={d.progression_summary} hideIds/></article><article className="panel"><h2>Failed or carryover courses</h2><ObjectDetails value={d.failed_courses} hideIds/></article></>}</AsyncPage>;
export const StudentTranscriptPage=()=> <AsyncPage title="Transcript" load={studentApi.transcript}>{d=><><div className="stats"><StatCard label="Student" value={d.student_name}/><StatCard label="Programme" value={`${d.programme_name} (${d.programme_code})`}/><StatCard label="CGPA" value={d.cgpa}/><StatCard label="Standing" value={d.academic_standing}/></div>{d.academic_sessions.length?d.academic_sessions.map(s=><section className="panel" key={s.academic_session_id}><h2>{s.academic_session_name}</h2>{s.semesters.map(semester=><section key={semester.semester_id}><h3>{semester.semester_name} · GPA {semester.gpa}</h3><DataTable<TranscriptCourse> rows={semester.courses} columns={[{key:'course_code',label:'Code'},{key:'course_title',label:'Course'},{key:'credit_units',label:'Units'},{key:'final_score',label:'Score'},{key:'grade_letter',label:'Grade'}]}/></section>)}</section>):<EmptyState message="No published transcript results are available."/>}</>}</AsyncPage>;
export const StudentClearancePage=()=> <AsyncPage title="Clearance" load={studentApi.clearance}>{d=><><div className="stats"><StatCard label="Overall status" value={<StatusBadge value={d.is_fully_cleared?'Fully cleared':'Pending'}/>}/><StatCard label="Pending" value={d.pending_count}/></div><DataTable<ClearanceItem> rows={d.requirements} columns={[{key:'name',label:'Requirement'},{key:'code',label:'Code'},{key:'is_mandatory',label:'Type',render:r=>r.is_mandatory?'Mandatory':'Optional'},{key:'status',label:'Status',render:r=><StatusBadge value={r.status}/>},{key:'remarks',label:'Remarks'}]}/></>}</AsyncPage>;
export const StudentDocumentsPage=()=> <AsyncPage title="Documents" load={studentApi.documents}>{rows=><DataTable<StudentDocument> rows={rows} columns={[{key:'type',label:'Type'},{key:'reference',label:'Reference'},{key:'status',label:'Status',render:r=><StatusBadge value={r.status}/>},{key:'issued_at',label:'Issue date',render:r=>r.issued_at?new Date(r.issued_at).toLocaleDateString():'—'},{key:'verification_code',label:'Verification code'}]}/>}</AsyncPage>;
