import {render,screen,waitFor} from '@testing-library/react';import userEvent from '@testing-library/user-event';import {MemoryRouter} from 'react-router-dom';import {beforeEach,describe,expect,it,vi} from 'vitest';import App from '../App';import {AuthProvider} from '../features/auth/AuthContext';import {session} from '../api/client';import {EmptyState,ErrorState,LoadingState} from '../components/States';
const student={id:'u1',institution_id:'i1',institution_code:'NSC',email:'student@example.edu',first_name:'Ada',last_name:'Okafor',phone:null,is_active:true,is_verified:true,roles:['student']};
const lecturer={...student,id:'u2',first_name:'Tunde',roles:['lecturer']};const admin={...student,id:'u3',roles:['administrator']};
const response=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}}));
function mockRoutes(routes:Record<string,unknown>){vi.stubGlobal('fetch',vi.fn((input:string|URL|Request,init?:RequestInit)=>{const path=new URL(String(input)).pathname;const value=routes[`${init?.method??'GET'} ${path}`]??routes[path];return value instanceof Response?Promise.resolve(value):response(value??{detail:'Not found'},value===undefined?404:200)}))}
function renderApp(path='/'){return render(<MemoryRouter initialEntries={[path]}><AuthProvider><App/></AuthProvider></MemoryRouter>)}
beforeEach(()=>sessionStorage.clear());
describe('authentication and routing',()=>{
 it('renders an accessible login form',()=>{renderApp('/login');expect(screen.getByRole('heading',{name:/welcome back/i})).toBeInTheDocument();expect(screen.getByLabelText(/institution code/i)).toBeInTheDocument();expect(screen.getByLabelText(/password/i)).toHaveAttribute('type','password')});
 it('successful login stores only the token and reaches the student portal',async()=>{mockRoutes({'POST /api/v1/auth/login':{access_token:'safe-token',token_type:'bearer',expires_in:900},'/api/v1/auth/me':student,'/api/v1/student-portal/dashboard':{...student,student_id:'s1',matriculation_number:'NSC/1',full_name:'Ada Okafor',programme_name:'Computer Science',programme_code:'CSC',programme_id:'p1',current_level:'200',admission_year:2025,enrollment_status:'active',current_academic_session:'2025/2026',current_semester:'First',registered_course_count:4,active_course_count:4,attendance_summary:{percentage:'92'},current_gpa:'4.20',cgpa:'4.10',academic_standing:'good',progression_summary:null,clearance_summary:null,graduation_summary:null}});renderApp('/login');const u=userEvent.setup();await u.type(screen.getByLabelText(/institution code/i),'NSC');await u.type(screen.getByLabelText(/email address/i),'student@example.edu');await u.type(screen.getByLabelText(/password/i),'secret-password');await u.click(screen.getByRole('button',{name:/sign in/i}));expect(await screen.findByText(/academic overview/i)).toBeInTheDocument();expect(session.get()).toBe('safe-token');expect(document.body).not.toHaveTextContent('secret-password')});
 it('shows a safe failed-login error',async()=>{mockRoutes({'POST /api/v1/auth/login':new Response(JSON.stringify({detail:'Invalid credentials'}),{status:401,headers:{'Content-Type':'application/json'}})});renderApp('/login');const u=userEvent.setup();await u.type(screen.getByLabelText(/institution code/i),'NSC');await u.type(screen.getByLabelText(/email/i),'a@b.com');await u.type(screen.getByLabelText(/password/i),'bad');await u.click(screen.getByRole('button',{name:/sign in/i}));expect(await screen.findByRole('alert')).toHaveTextContent('Invalid credentials')});
 it('redirects an unauthenticated protected route',async()=>{renderApp('/student/dashboard');expect(await screen.findByRole('heading',{name:/welcome back/i})).toBeInTheDocument()});
 it.each([[student,'/admin/dashboard'],[lecturer,'/student/dashboard']])('blocks cross-portal navigation',async(identity,path)=>{session.set('token');mockRoutes({'/api/v1/auth/me':identity});renderApp(path);expect(await screen.findByRole('heading',{name:/access restricted/i})).toBeInTheDocument()});
 it.each([[lecturer,'/lecturer/dashboard','teaching overview'],[admin,'/admin/dashboard','Institution overview']])('routes supported portal identities',async(identity,path,heading)=>{session.set('token');const api=path.includes('lecturer')?'/api/v1/lecturer-portal/dashboard':'/api/v1/admin-portal/dashboard';const data=path.includes('lecturer')?{lecturer_id:'l1',staff_number:'L1',name:'Tunde Okafor',department:'Science',employment_status:'active',active_course_assignment_count:0,current_course_offering_count:0,upcoming_class_session_count:0,total_registered_students:0,pending_assessment_component_count:0,completed_examination_count:0}:{institution_id:'i1',institution_name:'NSC',total_students:1,active_students:1,graduated_students:0,total_lecturers:1,active_lecturers:1,total_programmes:1,total_courses:1,current_academic_session:null,current_semester:null,active_course_offerings:0,active_course_registrations:0,published_results:0,pending_result_approvals:0,graduation_eligible_students:null,confirmed_graduations:0,issued_transcripts:0,issued_certificates:0,pending_mandatory_clearances:0};mockRoutes({'/api/v1/auth/me':identity,[api]:data});renderApp(path);expect(await screen.findByText(new RegExp(heading,'i'))).toBeInTheDocument()});
 it('logout clears the session',async()=>{session.set('token');mockRoutes({'/api/v1/auth/me':student,'/api/v1/student-portal/dashboard':{}});renderApp('/student/dashboard');await screen.findByRole('button',{name:/log out/i});await userEvent.click(screen.getByRole('button',{name:/log out/i}));expect(session.get()).toBeNull();expect(await screen.findByRole('heading',{name:/welcome back/i})).toBeInTheDocument()});
});
describe('API-driven UI states',()=>{
 it('renders student courses returned by the backend',async()=>{session.set('token');mockRoutes({'/api/v1/auth/me':student,'/api/v1/student-portal/courses':[{course_registration_id:'r1',course_offering_id:'o1',course_id:'c1',course_code:'CSC101',title:'Programming',credit_units:3,course_type:'core',semester_id:'s1',semester:'First',academic_session_id:'a1',academic_session:'2025/26',registration_status:'registered'}]});renderApp('/student/courses');expect(await screen.findByText('CSC101')).toBeInTheDocument();expect(screen.getByText('Programming')).toBeInTheDocument()});
 it('renders shared loading, error, and empty states',()=>{const {rerender}=render(<LoadingState/>);expect(screen.getByRole('status')).toBeInTheDocument();rerender(<ErrorState error={new Error('Safe message')}/>);expect(screen.getByRole('alert')).toHaveTextContent('Safe message');rerender(<EmptyState/>);expect(screen.getByText(/no records/i)).toBeInTheDocument()});
 it('clears an invalid session after an authenticated 401',async()=>{session.set('expired');mockRoutes({'/api/v1/auth/me':new Response(JSON.stringify({detail:'Token expired'}),{status:401,headers:{'Content-Type':'application/json'}})});renderApp('/student/dashboard');await waitFor(()=>expect(session.get()).toBeNull());expect(await screen.findByRole('heading',{name:/welcome back/i})).toBeInTheDocument()});
});

describe('admin record navigation',()=>{
 const dashboard={institution_id:'i1',institution_name:'Ngozi University',total_students:2,active_students:2,graduated_students:0,total_lecturers:1,active_lecturers:1,total_programmes:1,total_courses:1,current_academic_session:'2025/2026',current_semester:'First',active_course_offerings:1,active_course_registrations:2,published_results:0,pending_result_approvals:0,graduation_eligible_students:null,confirmed_graduations:0,issued_transcripts:0,issued_certificates:0,pending_mandatory_clearances:0};
 it('renders functional Admin overview, student, and offering navigation',async()=>{session.set('token');mockRoutes({'/api/v1/auth/me':admin,'/api/v1/admin-portal/dashboard':dashboard});renderApp('/admin/dashboard');expect(await screen.findByRole('link',{name:/overview/i})).toHaveAttribute('href','/admin/dashboard');expect(screen.getByRole('link',{name:'Students'})).toHaveAttribute('href','/admin/students');expect(screen.getByRole('link',{name:'Course offerings'})).toHaveAttribute('href','/admin/course-offerings');expect(await screen.findByRole('link',{name:/view students/i})).toBeInTheDocument()});
 it('renders backend students and navigates View Summary with the record ID',async()=>{session.set('token');mockRoutes({'/api/v1/auth/me':admin,'/api/v1/students':[{id:'student-42',matriculation_number:'NSC/2025/042',first_name:'Ada',last_name:'Okafor',programme_id:'p1',current_level:'200',enrollment_status:'active'}],'/api/v1/programmes':[{id:'p1',name:'Computer Science'}],'/api/v1/admin-portal/students/student-42/summary':{student_id:'student-42',identity:{name:'Ada Okafor'},programme:{name:'Computer Science'},current_level:'200',enrollment_status:'active',course_registration_count:0,attendance_headline:{},academic_performance:null,progression:null,graduation_eligibility:null,clearance:null,transcript_status:null,graduation_status:null,document_statuses:{}}});renderApp('/admin/students');expect(await screen.findByText('NSC/2025/042')).toBeInTheDocument();expect(screen.getByText('Computer Science')).toBeInTheDocument();await userEvent.click(screen.getByRole('link',{name:/view summary/i}));expect(await screen.findByRole('heading',{name:/student summary/i})).toBeInTheDocument();expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/admin-portal/students/student-42/summary'),expect.anything())});
 it('renders backend offerings and requests the selected summary endpoint',async()=>{session.set('token');mockRoutes({'/api/v1/auth/me':admin,'/api/v1/course-offerings':[{id:'offering-9',course_id:'c1',academic_session_id:'a1',semester_id:'s1',status:'active',registration_open:true}],'/api/v1/courses':[{id:'c1',code:'CSC401',title:'Distributed Systems',credit_units:3}],'/api/v1/academic-sessions':[{id:'a1',name:'2025/2026'}],'/api/v1/semesters':[{id:'s1',name:'First Semester'}],'/api/v1/admin-portal/course-offerings/offering-9/summary':{course_offering_id:'offering-9',course:{code:'CSC401'},academic_session:{name:'2025/2026'},semester:{name:'First Semester'},lecturer_assignments:[],registered_student_count:0,class_session_count:0,attendance_headline:{},assessment_component_count:0,examination_count:0,result_status_summary:{}}});renderApp('/admin/course-offerings');expect(await screen.findByText('CSC401')).toBeInTheDocument();expect(screen.getByText('Distributed Systems')).toBeInTheDocument();await userEvent.click(screen.getByRole('link',{name:/view summary/i}));expect(await screen.findByRole('heading',{name:/course offering summary/i})).toBeInTheDocument();expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/admin-portal/course-offerings/offering-9/summary'),expect.anything())});
 it('marks the active Admin navigation destination',async()=>{session.set('token');mockRoutes({'/api/v1/auth/me':admin,'/api/v1/students':[],'/api/v1/programmes':[]});renderApp('/admin/students');const link=await screen.findByRole('link',{name:'Students'});expect(link).toHaveAttribute('aria-current','page')});
});
