import {render,screen} from '@testing-library/react';import {MemoryRouter} from 'react-router-dom';import {beforeEach,describe,expect,it,vi} from 'vitest';import {DownloadAppPage} from '../pages/DownloadAppPage';import {LoginPage} from '../pages/LoginPage';import {AuthProvider} from '../features/auth/AuthContext';
const metadata={platform:'android',version:'1.0.0',version_code:1,filename:'ngozi-smart-campus-android-v1.0.0.apk',file_size:10485760,sha256:'a'.repeat(64),release_notes:'Initial public release.',released_at:'2026-08-17T12:00:00Z',download_url:'/api/v1/public/mobile-app/android/download'};
const response=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}}));
beforeEach(()=>{sessionStorage.clear()});
describe('public Android download',()=>{
 it('renders release metadata, checksum, CTA and safe installation guidance without auth',async()=>{vi.stubGlobal('fetch',vi.fn(()=>response(metadata)));render(<MemoryRouter><DownloadAppPage/></MemoryRouter>);expect(screen.getByRole('status')).toBeInTheDocument();expect(await screen.findByRole('heading',{name:/version 1\.0\.0/i})).toBeInTheDocument();expect(screen.getByText('10.0 MB')).toBeInTheDocument();expect(screen.getByText('a'.repeat(64))).toBeInTheDocument();expect(screen.getByText('Initial public release.')).toBeInTheDocument();const expectedDownloadUrl=new URL(metadata.download_url,import.meta.env.VITE_API_BASE_URL).toString();expect(screen.getByRole('link',{name:/download android apk/i})).toHaveAttribute('href',expectedDownloadUrl);expect(screen.getByText(/allow installation from this browser/i)).toBeInTheDocument();expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/public/mobile-app/android/latest'),expect.not.objectContaining({headers:expect.objectContaining({Authorization:expect.anything()})}))});
 it('renders a professional no-release state',async()=>{vi.stubGlobal('fetch',vi.fn(()=>response({detail:'Mobile App release not found'},404)));render(<MemoryRouter><DownloadAppPage/></MemoryRouter>);expect(await screen.findByText(/not available for public download yet/i)).toBeInTheDocument()});
 it('renders a safe API error state',async()=>{vi.stubGlobal('fetch',vi.fn(()=>response({detail:'Service unavailable'},503)));render(<MemoryRouter><DownloadAppPage/></MemoryRouter>);expect(await screen.findByRole('alert')).toHaveTextContent(/service unavailable/i)});
 it('exposes the download page from public login',()=>{render(<MemoryRouter><AuthProvider><LoginPage/></AuthProvider></MemoryRouter>);expect(screen.getByRole('link',{name:/download android app/i})).toHaveAttribute('href','/download-app')});
});
