import {render,screen} from '@testing-library/react';
import {describe,expect,it} from 'vitest';
import {StudentOverview} from '../components/StudentOverview';
import type {StudentDashboard} from '../types';

const uuid='5ae0e1bb-6998-4d85-a36e-38cff38345ba';
const dashboard={student_id:uuid,programme_id:uuid,matriculation_number:'NSC/2026/0001',first_name:'Test',last_name:'Student',full_name:'Test Student',email:'student@example.edu',phone:null,programme_name:'Bachelor of Science in Computing and Informatics',programme_code:'BSCI',current_level:'200',admission_year:2026,enrollment_status:'active',current_academic_session:'2026/2027',current_semester:'First Semester',registered_course_count:6,active_course_count:6,attendance_summary:{total_sessions:10,present_count:9},current_gpa:'4.10',cgpa:'4.20',academic_standing:'good_standing',progression_summary:{student_id:uuid,programme_id:uuid,current_academic_level_id:uuid,current_level:'200',next_academic_level_id:uuid,next_level:'300',cgpa:'4.20',academic_standing:'good_standing',has_carryover_courses:false,failed_course_count:0,eligible_for_progression:true,progression_reason:'requirements_satisfied'},clearance_summary:{student_id:uuid,is_fully_cleared:false,pending_count:1,cleared_count:1,waived_count:0,requirements:[{clearance_requirement_id:uuid,name:'Library Clearance',code:'LIB',sequence_number:1,is_mandatory:true,status:'pending'}]},graduation_summary:{student_id:uuid,programme_id:uuid,current_academic_level_id:uuid,cgpa:'4.20',minimum_graduation_cgpa:'1.50',academic_standing:'good_standing',total_published_courses:6,passed_course_count:6,outstanding_failed_course_count:0,final_level_reached:false,final_level:'400',eligible_for_graduation:false,eligibility_reasons:['final_level_not_reached'],outstanding_courses:[]}} satisfies StudentDashboard;

describe('Student Overview refinement',()=>{
  it('renders student-facing identity and academic summaries without UUIDs',()=>{render(<StudentOverview data={dashboard}/>);expect(screen.getByText('Test Student')).toBeInTheDocument();expect(screen.getByText('NSC/2026/0001')).toBeInTheDocument();expect(screen.getByText(/Bachelor of Science/)).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Academic Overview'})).toBeInTheDocument();expect(document.body).not.toHaveTextContent(uuid);expect(document.body).not.toHaveTextContent('Student Id');expect(document.body).not.toHaveTextContent('Programme Id')});
  it('renders progression, clearance, and graduation as explicit sections',()=>{render(<StudentOverview data={dashboard}/>);expect(screen.getByRole('heading',{name:'Academic Progress'})).toBeInTheDocument();expect(screen.getByText('Library Clearance')).toBeInTheDocument();expect(screen.getByText('LIB')).toBeInTheDocument();expect(screen.getAllByText('Mandatory').length).toBeGreaterThan(0);expect(screen.getByRole('heading',{name:'Graduation Eligibility'})).toBeInTheDocument();expect(screen.getByText('No outstanding courses.')).toBeInTheDocument()});
});
