import {Navigate,Route,Routes} from 'react-router-dom';
import {AdminLayout,GuardianLayout,LecturerLayout,StudentLayout} from './layouts/PortalLayout';
import {LoginPage} from './pages/LoginPage';import {NotFoundPage,UnauthorizedPage} from './pages/CommonPages';
import {AdminDashboardPage,AdminOfferingPage,AdminOfferingsPage,AdminStudentPage,AdminStudentsPage} from './pages/admin';
import {CourseAssessmentsPage,CourseAttendancePage,CourseExaminationsPage,CourseResultsPage,CourseStudentsPage,LecturerCoursesPage,LecturerDashboardPage} from './pages/lecturer';
import {StudentAttendancePage,StudentClearancePage,StudentCoursesPage,StudentDashboardPage,StudentDocumentsPage,StudentPerformancePage,StudentProfilePage,StudentResultsPage,StudentTranscriptPage} from './pages/student';
import {ChildAttendancePage,ChildClearancePage,ChildOverviewPage,ChildPerformancePage,ChildResultsPage,ChildTranscriptPage,GuardianChildrenPage,GuardianDashboardPage} from './pages/guardian';
import {ProtectedRoute,RoleRoute} from './routes/guards';import {portalFor,useAuth} from './features/auth/AuthContext';import {LoadingState} from './components/States';
function Home(){const {user,loading}=useAuth();return loading?<LoadingState/>:<Navigate to={user?portalFor(user.roles):'/login'} replace/>}
export default function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/login" element={<LoginPage/>}/><Route path="/unauthorized" element={<UnauthorizedPage/>}/><Route element={<ProtectedRoute/>}>
<Route element={<RoleRoute allowed={['guardian']}/>}><Route path="guardian" element={<GuardianLayout/>}><Route index element={<Navigate to="dashboard" replace/>}/><Route path="dashboard" element={<GuardianDashboardPage/>}/><Route path="children" element={<GuardianChildrenPage/>}/><Route path="children/:studentId" element={<ChildOverviewPage/>}/><Route path="children/:studentId/results" element={<ChildResultsPage/>}/><Route path="children/:studentId/attendance" element={<ChildAttendancePage/>}/><Route path="children/:studentId/performance" element={<ChildPerformancePage/>}/><Route path="children/:studentId/transcript" element={<ChildTranscriptPage/>}/><Route path="children/:studentId/clearance" element={<ChildClearancePage/>}/></Route></Route>
<Route element={<RoleRoute allowed={['student']}/>}><Route path="student" element={<StudentLayout/>}><Route index element={<Navigate to="dashboard" replace/>}/><Route path="dashboard" element={<StudentDashboardPage/>}/><Route path="profile" element={<StudentProfilePage/>}/><Route path="courses" element={<StudentCoursesPage/>}/><Route path="attendance" element={<StudentAttendancePage/>}/><Route path="results" element={<StudentResultsPage/>}/><Route path="performance" element={<StudentPerformancePage/>}/><Route path="transcript" element={<StudentTranscriptPage/>}/><Route path="clearance" element={<StudentClearancePage/>}/><Route path="documents" element={<StudentDocumentsPage/>}/></Route></Route>
<Route element={<RoleRoute allowed={['lecturer']}/>}><Route path="lecturer" element={<LecturerLayout/>}><Route index element={<Navigate to="dashboard" replace/>}/><Route path="dashboard" element={<LecturerDashboardPage/>}/><Route path="courses" element={<LecturerCoursesPage/>}/><Route path="course-offerings/:id/students" element={<CourseStudentsPage/>}/><Route path="course-offerings/:id/attendance" element={<CourseAttendancePage/>}/><Route path="course-offerings/:id/assessments" element={<CourseAssessmentsPage/>}/><Route path="course-offerings/:id/examinations" element={<CourseExaminationsPage/>}/><Route path="course-offerings/:id/results" element={<CourseResultsPage/>}/></Route></Route>
<Route element={<RoleRoute allowed={['administrator','system_super_admin']}/>}><Route path="admin" element={<AdminLayout/>}><Route index element={<Navigate to="dashboard" replace/>}/><Route path="dashboard" element={<AdminDashboardPage/>}/><Route path="students" element={<AdminStudentsPage/>}/><Route path="students/:studentId" element={<AdminStudentPage/>}/><Route path="course-offerings" element={<AdminOfferingsPage/>}/><Route path="course-offerings/:courseOfferingId" element={<AdminOfferingPage/>}/></Route></Route></Route><Route path="*" element={<NotFoundPage/>}/></Routes>}
