import type React from 'react';
import type {StudentDashboard} from '../types';
import './student-overview.css';
import {EmptyState} from './States';
import {DisplayValue,StatCard,StatusBadge} from './UI';

type ValueMap=Record<string,React.ReactNode>;
const record=(value:unknown):ValueMap=>value&&typeof value==='object'&&!Array.isArray(value)?value as ValueMap:{};
const list=(value:unknown):ValueMap[]=>Array.isArray(value)?value.filter(item=>item&&typeof item==='object') as ValueMap[]:[];
const present=(value:unknown)=>value!==null&&value!==undefined&&value!=='';
const Field=({label,value,badge=false}:{label:string;value:unknown;badge?:boolean})=>present(value)?<div><dt>{label}</dt><dd>{badge?<StatusBadge value={typeof value==='boolean'?value:String(value)}/>:<DisplayValue value={value}/>}</dd></div>:null;

function Progression({value}:{value:unknown}){const item=record(value);if(!Object.keys(item).length)return <EmptyState message="No academic progression evaluation is available."/>;return <dl className="student-field-grid"><Field label="Current level" value={item.current_level}/><Field label="Next level" value={item.next_level}/><Field label="CGPA" value={item.cgpa}/><Field label="Academic standing" value={item.academic_standing} badge/><Field label="Carryover courses" value={item.has_carryover_courses?'Yes':'No'} badge/><Field label="Failed courses" value={item.failed_course_count}/><Field label="Progression eligibility" value={item.eligible_for_progression?'Eligible':'Not eligible'} badge/><Field label="Reason" value={item.progression_reason}/></dl>}

function Clearance({value}:{value:unknown}){const item=record(value),requirements=list(item.requirements);if(!Object.keys(item).length)return <EmptyState message="No clearance records available."/>;return <><div className="student-summary-strip"><StatCard label="Overall status" value={<StatusBadge value={item.is_fully_cleared?'Fully cleared':'Pending'}/>} /><StatCard label="Pending requirements" value={item.pending_count as React.ReactNode}/><StatCard label="Cleared or waived" value={Number(item.cleared_count??0)+Number(item.waived_count??0)}/></div>{requirements.length?<div className="student-requirements">{requirements.map((requirement,index)=><article key={`${String(requirement.code??'requirement')}-${index}`}><div><h3>{String(requirement.name??'Clearance requirement')}</h3>{present(requirement.code)&&<span>{String(requirement.code)}</span>}</div><div className="requirement-meta"><StatusBadge value={requirement.is_mandatory?'Mandatory':'Optional'}/><StatusBadge value={String(requirement.status??'Pending')}/></div>{present(requirement.remarks)&&<p>{String(requirement.remarks)}</p>}</article>)}</div>:<EmptyState message="No clearance requirements are available."/>}</>}

function Graduation({value}:{value:unknown}){const item=record(value),outstanding=list(item.outstanding_courses);if(!Object.keys(item).length)return <EmptyState message="Graduation eligibility has not been evaluated yet."/>;const reasons=Array.isArray(item.eligibility_reasons)?item.eligibility_reasons.map(String):[];return <><dl className="student-field-grid"><Field label="Graduation eligibility" value={item.eligible_for_graduation?'Eligible':'Not eligible'} badge/><Field label="Current CGPA" value={item.cgpa}/><Field label="Minimum required CGPA" value={item.minimum_graduation_cgpa}/><Field label="Academic standing" value={item.academic_standing} badge/><Field label="Published courses" value={item.total_published_courses}/><Field label="Passed courses" value={item.passed_course_count}/><Field label="Outstanding failed courses" value={item.outstanding_failed_course_count}/><Field label="Final level reached" value={item.final_level_reached?'Yes':'No'} badge/><Field label="Final level" value={item.final_level}/><Field label="Eligibility reason" value={reasons.length?reasons.join(', '):item.eligible_for_graduation?'All requirements satisfied':'Not available'}/></dl>{outstanding.length?<div className="student-course-list">{outstanding.map((course,index)=><div key={`${String(course.course_code??'course')}-${index}`}><strong>{String(course.course_code??'Course')}</strong><span>{String(course.course_title??'Outstanding course')}</span></div>)}</div>:<p className="student-empty-line">No outstanding courses.</p>}</>}

export function StudentOverview({data:d}:{data:StudentDashboard}){const attendance=record(d.attendance_summary),total=Number(attendance.total_sessions??0),presentCount=Number(attendance.present_count??0),attendanceRate=total?`${Math.round(presentCount*100/total)}%`:'No sessions';const graduation=record(d.graduation_summary),clearance=record(d.clearance_summary);return <><header className="student-identity"><div><span>Student Overview</span><h2>{d.full_name}</h2><strong>{d.matriculation_number}</strong><p>{d.programme_name??'Programme not available'}{d.current_level?` · ${d.current_level} Level`:''}</p></div><StatusBadge value={d.enrollment_status}/></header><section aria-labelledby="academic-overview"><div className="student-section-heading"><span>Current academic information</span><h2 id="academic-overview">Academic Overview</h2></div><div className="student-overview-stats"><StatCard label="CGPA" value={d.cgpa}/><StatCard label="Academic standing" value={d.academic_standing?<StatusBadge value={d.academic_standing}/>:null}/><StatCard label="Published courses/results" value={graduation.total_published_courses??'Not available'}/><StatCard label="Attendance" value={attendanceRate}/><StatCard label="Current level" value={d.current_level}/><StatCard label="Clearance" value={Object.keys(clearance).length?<StatusBadge value={clearance.is_fully_cleared?'Fully cleared':'Pending'}/>:null}/></div><div className="student-period"><span>{d.current_academic_session??'Current session unavailable'}</span><span>{d.current_semester??'Current semester unavailable'}</span><span>{d.registered_course_count} registered courses</span></div></section><div className="student-dashboard-sections"><section className="panel student-wide-panel"><h2>Academic Progress</h2><Progression value={d.progression_summary}/></section><section className="panel student-wide-panel"><h2>Clearance</h2><Clearance value={d.clearance_summary}/></section><section className="panel student-wide-panel"><h2>Graduation Eligibility</h2><Graduation value={d.graduation_summary}/></section></div></>}
